/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sewalapanganfutsal;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danzeld
 */
public class FormLapangan extends javax.swing.JFrame {

    /**
     * Creates new form FormLapangan
     */
    
    public FormLapangan() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadData();
    }
    
    
    private void loadData(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Lapangan");
        model.addColumn("Nama Lapangan");
        model.addColumn("Harga Sewa");
        model.addColumn("Status");
        
        DecimalFormat formatter = new DecimalFormat("'Rp '#,##0");
        
        try {
            Connection  conn = DBConnection.getConnection();
            Set<Integer>bookedIds = new HashSet<>();
            String bookedSql = "SELECT id_lapangan From booking " +
                               "WHERE tanggal_booking = CURDATE() " +
                               "AND CURTIME() BETWEEN jam_mulai AND jam_selesai";
            
            try (Statement stmtBooked = conn.createStatement();
                 ResultSet rsBooked = stmtBooked.executeQuery(bookedSql)){
                while (rsBooked.next()){
                    bookedIds.add(rsBooked.getInt("id_lapangan"));
                }
            }
            
            String allFieldsSql = "SELECT id_lapangan, nama_lapangan, harga FROM lapangan ORDER BY id_lapangan ASC";
            try (Statement stmtFields = conn.createStatement();
                 ResultSet rsFields = stmtFields.executeQuery(allFieldsSql)) {
                
                while (rsFields.next()) {
                    int id = rsFields.getInt("id_lapangan");
                    String nama = rsFields.getString("nama_lapangan");
                    double harga = rsFields.getDouble("harga");
                    
                    String status;
                    if (bookedIds.contains(id)){
                        status = "Sedang Digunakan";
                    } else {
                        status = "Tersedia";
                    }
                    
                    String hargaFormatted = formatter.format(harga);
                    
                    model.addRow(new Object[]{id, nama, hargaFormatted, status});
                    
                }
            }
            
            jTable1.setModel(model);
            if (jTable1.getColumnCount() > 3){
                jTable1.getColumnModel().getColumn(3).setCellRenderer(new StatusCellRenderer());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data lapangan: " + e.getMessage());
            e.printStackTrace();
        }
    }
              
    
    public class Lapangan {
        private int id;
        private String nama;
        private double harga;
        
        public Lapangan(int id, String nama, double harga) {
            this.id = id;
            this.nama = nama;
            this.harga = harga;
        }
        
        public int getId() {
            return id;
        }
        public String getNama() {
            return nama;
        }
        public double getHarga(){
            return harga;
        }
        @Override
        public String toString(){
            return this.nama;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLapangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
