/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sewalapanganfutsal;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Danzeld
 */
public class FormBooking extends javax.swing.JFrame {

    /**
     * Creates new form BookingForm
     */
    public FormBooking() {
        initComponents();
        loadDataLapangan();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    
    private void loadDataLapangan(){
        String sql = "SELECT id_lapangan, nama_lapangan FROM lapangan ORDER BY nama_lapangan ASC";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()){
            
            cmbLapangan.removeAllItems();
            
            while (rs.next()) {
            int id = rs.getInt("id_lapangan");
            String nama = rs.getString("nama_lapangan");
            cmbLapangan.addItem(new ItemLapangan(id, nama));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data lapangan: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        cmbLapangan = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox2 = new javax.swing.JComboBox();
        jSpinField1 = new com.toedter.components.JSpinField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama Customer");

        jLabel2.setText("No Telepon");

        jLabel3.setText("Pilih Lapangan");

        jLabel4.setText("Tanggal Booking");

        jLabel5.setText("Jam Mulai");

        jLabel6.setText("Durasi");

        jLabel7.setText("Total Biaya");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        cmbLapangan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lapangan A", "Lapangan B", "Lapangan C" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jSpinField1.setValue(1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Jam");

        jTextField3.setEditable(false);

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(cmbLapangan, 0, 186, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpinField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String namaCustomer = jTextField1.getText();
        String noTelp = jTextField2.getText();
        
        Object selectedItemObject = cmbLapangan.getSelectedItem();
        Date tanggalBooking = jDateChooser1.getDate();


        if (namaCustomer.isEmpty() || noTelp.isEmpty() || selectedItemObject == null || tanggalBooking == null) {
            JOptionPane.showMessageDialog(this, "Semua data wajib diisi!", "Input tidak lengkap", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ItemLapangan itemTerpilih = (ItemLapangan) selectedItemObject;
        int idLapangan = itemTerpilih.getId();
             
        
        try {
            long idCustomer = dapatkanAtauBuatIdCustomer(namaCustomer, noTelp);
            if (idCustomer == 0) {
                JOptionPane.showMessageDialog(this, "Gagal memproses data customer!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int hargaPerjam = getHargaPerjam(idLapangan);
            int durasi = jSpinField1.getValue();
            int totalBiaya = hargaPerjam * durasi;
            jTextField3.setText(String.valueOf(totalBiaya));
            
            SimpleDateFormat sdfTime = new SimpleDateFormat("HH:mm:ss");
            String jamMulaiStr = jComboBox2.getSelectedItem().toString() + ":00:00";
            Calendar cal = Calendar.getInstance();
            cal.setTime(sdfTime.parse(jamMulaiStr));
            cal.add(Calendar.HOUR_OF_DAY, durasi);
            String jamSelesaiStr = sdfTime.format(cal.getTime());
            
            String sqlBooking = "INSERT INTO booking(id_lapangan, id_customer, tanggal_booking, jam_mulai, jam_selesai, total_biaya, status) VALUES (?, ?, ?, ?, ?, ?, ?)";
            Connection conn = DBConnection.getConnection();
            PreparedStatement pstBooking = conn.prepareStatement(sqlBooking, Statement.RETURN_GENERATED_KEYS);
            
            pstBooking.setInt(1, idLapangan);
            pstBooking.setLong(2, idCustomer);
            pstBooking.setDate(3, new java.sql.Date(tanggalBooking.getTime()));
            pstBooking.setString(4, jamMulaiStr);
            pstBooking.setString(5, jamSelesaiStr);
            pstBooking.setInt(6, totalBiaya);
            pstBooking.setString(7, "Booked");
            
            int rowsAffected = pstBooking.executeUpdate();
            
            if(rowsAffected > 0) {
                ResultSet generatedKeys = pstBooking.getGeneratedKeys();
                int idBookingBaru = 0;
                if (generatedKeys.next()){
                    idBookingBaru = generatedKeys.getInt(1);
                }
                
                String teksStruk = buatTeksStruk(
                        idBookingBaru, 
                        namaCustomer, 
                        itemTerpilih.getNama(), 
                        tanggalBooking, 
                        jamMulaiStr, 
                        jamSelesaiStr, 
                        totalBiaya 
                );
                JTextArea textArea = new JTextArea(teksStruk);
                textArea.setEditable(false);
                textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
                JScrollPane scrollPane = new JScrollPane(textArea);
                JOptionPane.showMessageDialog(this, scrollPane, "Booking Berhasil", JOptionPane.INFORMATION_MESSAGE);
                kosongkanForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi error saat proses Booking" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBooking().setVisible(true);
            }
        });
    }
    
        private int dapatkanIdLapangan(String namaLapangan) {
        String sql = "SELECT id_lapangan FROM lapangan WHERE nama_lengkap = ?";
        try (Connection conn = DBConnection.getConnection()) {
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, namaLapangan);
            try (ResultSet rs = pst.executeQuery()) {
                if(rs.next()) {
                    return rs.getInt("id_lapangan");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return 0;
    }

    private int getHargaPerjam(int idLapangan) throws SQLException {
        String sql = "SELECT harga FROM lapangan WHERE id_lapangan = ?";
        try (Connection conn = DBConnection.getConnection()) {
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, idLapangan);
            try (ResultSet rs = pst.executeQuery()) {
                if(rs.next()) {
                    return rs.getInt("harga");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return 0;
    }
    
        private long dapatkanAtauBuatIdCustomer(String nama, String telp) throws SQLException {
        long id = 0;
        String cekSql = "SELECT id_customer FROM customer WHERE no_telepon = ?";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstCek = conn.prepareStatement(cekSql)) {
            
            pstCek.setString(1, telp);
            try (ResultSet rs = pstCek.executeQuery()) {
                if (rs.next()) {
                    id = rs.getLong("id_customer");
                } else {
                    String insertSql = "INSERT INTO customer (nama_customer, no_telepon) VALUES (?, ?)";
                    try (PreparedStatement pstInsert = conn.prepareStatement(insertSql, Statement.RETURN_GENERATED_KEYS)) {
                        pstInsert.setString(1, nama);
                        pstInsert.setString(2, telp);
                        pstInsert.executeUpdate();
                        try (ResultSet generatedKeys = pstInsert.getGeneratedKeys()){
                            if (generatedKeys.next()) {
                                id = generatedKeys.getLong(1);
                            }
                        }
                    }
                }
            }
        }
        return id;
    }
    
    private String buatTeksStruk(int idBooking, String namaCustomer, String namaLapangan, Date tanggal, String jamMulai, String jamSelesai, int totalBiaya){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tanggalStr = sdf.format(tanggal);
            
            Locale localeID = new Locale("in", "ID");
            NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(localeID);
            String hargaStr = formatRupiah.format(totalBiaya).replace(",00", "");
            String waktuMulaiLengkap = tanggalStr + " " + jamMulai;
            String waktuSelesaiLengkap = tanggalStr + " " + jamSelesai;
            
            StringBuilder sb = new StringBuilder();
            sb.append(" === Struk Booking Futsal ===\n\n");
            sb.append("ID Transaksi : ").append(idBooking).append("\n");
            sb.append("Nama Customer : ").append(namaCustomer).append("\n");
            sb.append("Nama Lapangan : ").append(namaLapangan).append("\n");
            sb.append("Waktu Mulai : ").append(waktuMulaiLengkap).append("\n");
            sb.append("Waktu Selesai : ").append(waktuSelesaiLengkap).append("\n");
            sb.append("Total Harga : ").append(hargaStr).append("\n\n");
            sb.append("==============================\n");
            sb.append("     Terima kasih!\n");
            
            return sb.toString();
            
    }
    
    private void kosongkanForm(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        
        if (cmbLapangan.getItemCount() > 0) {
            cmbLapangan.setSelectedIndex(0);
        }
        jDateChooser1.setDate(null);
        jSpinField1.setValue(1);
        jTextField1.requestFocus();
    }

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbLapangan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}



